config/routes.rb
Rails.application.routes.draw do
  devise_for :users


  root to: 'pages#main'

  resources :holidays
  get 'delete_holiday/:id', to: 'holidays#delete_request', as: :delete_holiday

  get 'holiday/:id/events', to: 'holidays#events', as: :holiday_events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/events/base_event.rb
# Kickstarter code reference:
# https://github.com/pcreux/event-sourcing-rails-todo-app-demo/blob/master/app/models/lib/base_event.rb

class Events::BaseEvent < ActiveRecord::Base
  delegate :aggregate_name, to: :class

  before_validation :find_or_build_aggregate
  before_create :apply_and_persist

  self.abstract_class = true

  def apply(aggregate)
    raise NotImplementedError
  end

  after_initialize do
    self.event_type = event_type
    self.payload ||= {}
  end

  def self.payload_attributes(*attributes)
    @payload_attributes ||= []

    attributes.map(&:to_s).each do |attribute|
      @payload_attributes << attribute unless @payload_attributes.include?(attribute)

      define_method attribute do
        self.payload ||= {}
        self.payload[attribute]
      end

      define_method "#{attribute}=" do |argument|
        self.payload ||= {}
        self.payload[attribute] = argument
      end
    end

    @payload_attributes
  end

  def aggregate=(model)
    public_send("#{aggregate_name}=", model)
  end

  def aggregate
    public_send(aggregate_name)
  end

  def aggregate_id=(id)
    public_send "#{aggregate_name}_id=", id
  end

  def aggregate_id
    public_send "#{aggregate_name}_id"
  end

  def self.aggregate_name
    @aggregate_name||= begin
      inferred_aggregate = reflect_on_all_associations(:belongs_to).first
      raise "Events must belong to an aggregate" if inferred_aggregate.nil?
      inferred_aggregate.name
    end
  end

  def event_klass
    klass = self.class.to_s.split("::")
    klass[-1] = event_type
    klass.join('::').constantize
  end

  private

  def apply_and_persist
    # Lock the database row! (OK because we're in an ActiveRecord callback chain transaction)
    aggregate.lock! if aggregate.persisted?

    # Apply!
    self.aggregate = apply(aggregate)

    #Persist!
    aggregate.save!
    self.aggregate_id = aggregate.id if aggregate_id.nil?
  end
  
  def find_or_build_aggregate
    self.aggregate = find_aggregate if aggregate_id.present?
    self.aggregate = build_aggregate if self.aggregate.nil?
  end

  def find_aggregate
    klass = aggregate_name.to_s.classify.constantize
    klass.find(aggregate_id)
  end

  def build_aggregate
    public_send "build_#{aggregate_name}"
  end


  def event_type
    self.attributes["event_type"] || self.class.to_s
  end
end

app/models/events/holiday/base_event.rb
class Events::Holiday::BaseEvent < Events::BaseEvent
  self.table_name = "holiday_events"
  self.inheritance_column = :event_type
  
  belongs_to :holiday, class_name: "::Holiday"
end

app/models/events/holiday/created.rb
class Events::Holiday::Created < Events::Holiday::BaseEvent

  payload_attributes :date, :user, :created_by, :modified_by, :deleted

  def apply(holiday)
    holiday.date = date
    holiday.user_id = user 
    holiday.created_by_id = created_by
    holiday.deleted = deleted
  
    holiday
  end
end

app/models/events/holiday/deleted.rb
class Events::Holiday::Deleted < Events::Holiday::BaseEvent

  payload_attributes :date, :user, :created_by, :modified_by, :deleted

  def apply(holiday)
    holiday.deleted = true
    holiday.modified_by_id = modified_by
  
    holiday
  end
end

app/models/events/holiday/updated.rb
class Events::Holiday::Updated < Events::Holiday::BaseEvent

  payload_attributes :date, :user, :created_by, :modified_by, :deleted, :holiday_id

  def apply(holiday)
    holiday.date = date if date
    holiday.modified_by_id = modified_by
  
    holiday
  end
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  belongs_to :user
  belongs_to :creator, class_name: 'User', foreign_key: "created_by_id"
  belongs_to :modifier, class_name: 'User', foreign_key: "modified_by_id", optional: true

  has_many :events, class_name: "Events::Holiday::BaseEvent"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :holidays, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token, only: [:create, :destroy]
  before_action :authenticate_user!

end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :set_holiday, only: [:edit, :events]

  def index
    @holidays = current_user.holidays.includes(:creator, :modifier).order(:date)
  end

  def new
    @holiday = Holiday.new
  end

  def create
    Events::Holiday::Created.create(payload: holiday_params.merge(user: current_user.id,
                                                                  created_by: current_user.id))
    redirect_to holidays_path
  end

  def edit; end

  def update
    Events::Holiday::Updated.create(payload: holiday_params.merge(modified_by: current_user.id), holiday_id: params[:id])
    redirect_to holidays_path
  end

  def delete_request
    set_holiday
  end

  def destroy
    Events::Holiday::Deleted.create(payload: {}, holiday_id: params[:id])
    redirect_to holidays_path
  end

  def events
    @events = @holiday.events
  end

  private

  def set_holiday
    @holiday = Holiday.find(params[:id])
  end
 
  def holiday_params
    params.require(:holiday).permit(:date, :user, :deleted)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/holidays/delete_request.html.erb
<h1>Delete this holiday?</h1>
<div class="holiday-card">
  <h3>User: <%= @holiday.user.email.split(/@/).first %></h3>
  <p>id: <%= @holiday.id %></p>
  <p>Holiday date: <%= @holiday.date.strftime('%A, %b %d') %></p>
  <p>Holiday created by: <%= @holiday.creator.email.split(/@/).first %></p>
  <p>Updated: <%= @holiday.updated_at.strftime('%a, %e %b %Y %H:%M:%S') %>, by <%= @holiday.modifier.presence&.email&.split(/@/)&.first || @holiday.creator.email.split(/@/).first %></p>
</div>

<%= link_to 'Delete', holiday_path(@holiday), method: :delete %>

app/views/holidays/edit.html.erb
<%= form_with model: @holiday do |f| %>
  <%= f.date_field :date %>
  <%= f.submit %>
<% end %>

app/views/holidays/events.html.erb
<div>
  <% @events.each do |e| %>
    <p><%= e.class.to_s %></p>
    <p><%= e.payload %></p>
  <% end %>
</div>

app/views/holidays/index.html.erb
<h1>Your Holidays</h1>
<div class='create-holidays'>
  <%= link_to 'Add a new holiday', new_holiday_path, class: 'btn btn-primary' %>
</div>
<hr>
<% @holidays.each do |holiday| %>
  <div class="holiday-card">
    <div class='holiday-status'>
      <p><%= holiday.deleted ? 'deleted' : 'approved'%></p>
    </div>
    <%= link_to holiday_events_path(holiday) do %>
      <h3>User: <%= holiday.user.email.split(/@/).first %></h3>
      <p>id: <%= holiday.id %></p>
      <p>Holiday date: <%= holiday.date.strftime('%A, %b %d') %></p>
      <p>Holiday created by: <%= holiday.creator.email.split(/@/).first %></p>
      <p>Updated: <%= holiday.updated_at.strftime('%a, %e %b %Y %H:%M:%S') %>, by <%= holiday.modifier.presence&.email&.split(/@/)&.first || holiday.creator.email.split(/@/).first %></p>
    <% end %>
    <div>
      <%= link_to "Edit", edit_holiday_path(holiday) %>
    </div>
    <div>
      <% unless holiday.deleted? %>
        <%= link_to "Delete", delete_holiday_path(holiday) %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/holidays/new.html.erb
<div class='new-holiday text-center'>
  <h2>Take some time off</h2>
  <%= form_with model: @holiday do |f| %>
    <%= f.label :date %>
    <%= f.date_field :date, value: Date.today + 1 %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charleshr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="container d-flex justify-content-center home">
      <div class='align-self-center'>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/main.html.erb
<h1>Welcome to CharlesHR</h1>
<p>Unforgetful HR Software</p>
<% if user_signed_in? %>
  <p>current user: <%= current_user.email%></p>
    <p><%= link_to "Create of edit your holidays", holidays_path%></p >
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
<% else %>
  <%= link_to('Login', new_user_session_path) %>  
<% end %>